/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.AsuperArts.UI;

import br.com.AsuperArts.BLL.ClienteBLL;
import br.com.AsuperArts.BLL.EstoqueBLL;
import br.com.AsuperArts.BLL.ServicosBLL;
import br.com.AsuperArts.DTO.ClienteDTO;
import br.com.AsuperArts.DTO.EstoqueDTO;
import br.com.AsuperArts.DTO.ServicosDTO;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class Form_abrirOSNew extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_abrirOSNew
     */
    public Form_abrirOSNew() {
        ClienteBLL clienteBLL = new ClienteBLL();
        EstoqueBLL estoqueBLL= new EstoqueBLL();
        ServicosBLL servicosBLL = new ServicosBLL();
        initComponents();
        btn_add.setBorder(new RoundedBorder(12));
        btn_del.setBorder(new RoundedBorder(12));
        btn_abrir.setBorder(new RoundedBorder(12));
        btn_calc.setBorder(new RoundedBorder(12));
      
        
        txt_responsavel.setText(Tela_login.txtUsuario.getText());
        SimpleDateFormat fd = new  SimpleDateFormat("dd/MM/yyyy");
        txt_dtEntrada.setText( fd.format(new java.util.Date()));
        
        for(EstoqueDTO e : estoqueBLL.ListaEstoque()){
            txt_produtos.addItem(e.getNome());
        }
       
        for(ClienteDTO c : clienteBLL.listaCliente()){
            txt_empresa.addItem(c.getNome());
        }
        for(ServicosDTO S : servicosBLL.lista01()){
            txt_servico.addItem(S.getServico());
        }
    }
    private class RoundedBorder implements Border {

    private int radius;

    RoundedBorder(int radius) {
        this.radius = radius;
    }
    public Insets getBorderInsets(Component c) {
        return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
    }


    public boolean isBorderOpaque() {
        return true;
    }


    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawRoundRect(x,y,width-1,height-1,radius,radius);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_dtEntrada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_empresa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_produtos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_responsavel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_solicitante = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_observacoes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_unitario = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_os = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txt_entrega = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txt_cor = new javax.swing.JTextField();
        txt_servico = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txt_qtd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_totalCalc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_valorH = new javax.swing.JTextField();
        lbl_hora = new javax.swing.JLabel();
        txt_totalH = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_hora = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_valorI = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_base = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_totalI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_calc = new javax.swing.JButton();
        btn_abrir = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Abrir O.S ");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("aSuperArts - Comunicação Visual & Sinalização Arquitetônica");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sem valor fiscal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel10)
                .addGap(91, 91, 91)
                .addComponent(jLabel14)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14))))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Código");

        txt_cod.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Data de Entrada");

        txt_dtEntrada.setEditable(false);
        txt_dtEntrada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Empresa");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Serviço");

        txt_empresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        txt_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empresaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Material");

        txt_produtos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        txt_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Responsável");

        txt_responsavel.setEditable(false);
        txt_responsavel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Solicitante");

        txt_solicitante.setEditable(false);
        txt_solicitante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_solicitante.setText("-");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Observações");

        txt_observacoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_observacoes.setText("-");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Valor Unitário");

        txt_unitario.setEditable(false);
        txt_unitario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_unitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_unitario.setText("-");

        tb_os.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data de Entrada", "Cliente", "Empresa", "Serviço", "Material", "Cor", "Quantidade", "Valor Unitário", "Total", "Responsavel", "Observações", "V.Hora", "Tempo(Hora)", "Total", "V.Impressão", "Metragem(mm)", "Total", "Solicitante", "Data de Entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_os);
        if (tb_os.getColumnModel().getColumnCount() > 0) {
            tb_os.getColumnModel().getColumn(0).setResizable(false);
            tb_os.getColumnModel().getColumn(1).setResizable(false);
            tb_os.getColumnModel().getColumn(2).setResizable(false);
            tb_os.getColumnModel().getColumn(3).setResizable(false);
            tb_os.getColumnModel().getColumn(4).setResizable(false);
            tb_os.getColumnModel().getColumn(5).setResizable(false);
            tb_os.getColumnModel().getColumn(6).setResizable(false);
            tb_os.getColumnModel().getColumn(7).setResizable(false);
            tb_os.getColumnModel().getColumn(8).setResizable(false);
            tb_os.getColumnModel().getColumn(9).setResizable(false);
            tb_os.getColumnModel().getColumn(10).setResizable(false);
            tb_os.getColumnModel().getColumn(11).setResizable(false);
            tb_os.getColumnModel().getColumn(12).setResizable(false);
            tb_os.getColumnModel().getColumn(13).setResizable(false);
            tb_os.getColumnModel().getColumn(14).setResizable(false);
            tb_os.getColumnModel().getColumn(15).setResizable(false);
            tb_os.getColumnModel().getColumn(16).setResizable(false);
            tb_os.getColumnModel().getColumn(17).setResizable(false);
            tb_os.getColumnModel().getColumn(18).setResizable(false);
        }

        jScrollPane3.setViewportView(jScrollPane2);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Data de Entrega");

        txt_entrega.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Cor");

        txt_cor.setEditable(false);
        txt_cor.setText("-");

        txt_servico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_servico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        txt_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_servicoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Quantidade");

        txt_qtd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_qtd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_qtd.setText("-");
        txt_qtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qtdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qtdKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Total");

        txt_totalCalc.setEditable(false);
        txt_totalCalc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_totalCalc.setText("-");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Valor Hora");

        txt_valorH.setEditable(false);
        txt_valorH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_valorH.setText("-");

        lbl_hora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_hora.setText("Total");

        txt_totalH.setEditable(false);
        txt_totalH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_totalH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_totalH.setText("-");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Tempo(Hora)");

        txt_hora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_hora.setText("-");
        txt_hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_horaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_horaKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Valor Impressão");

        txt_valorI.setEditable(false);
        txt_valorI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_valorI.setText("-");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Base");

        txt_base.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_base.setText("-");
        txt_base.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_baseKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_baseKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Total");

        txt_totalI.setEditable(false);
        txt_totalI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_totalI.setText("-");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Valor Total");

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.setText("0.0");

        btn_calc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_calc.setText("Calcular");

        btn_abrir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_abrir.setText("Salvar O.S");

        btn_del.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_del.setText("Remover");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_add.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_add.setText("Adicionar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Altura");

        txt_altura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_altura.setText("-");
        txt_altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_alturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_alturaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cod))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(txt_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_dtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_empresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_totalCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_totalI, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_observacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_valorH, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_hora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_totalH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_valorI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(txt_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txt_totalCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_observacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(txt_totalI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valorI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txt_totalH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hora)
                    .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txt_valorH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txt_solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void preencherTabela() {
        this.tb_os.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_os.getModel();
        modelo.setNumRows(0);
        EstoqueBLL rg = new EstoqueBLL();
              
    }
    private void txt_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produtosActionPerformed
        txt_qtd.setEnabled(true);
        String NomeProduto = txt_produtos.getSelectedItem().toString();
        EstoqueBLL cb = new EstoqueBLL();
        EstoqueDTO produto = cb.listaEstoqueNome(NomeProduto);
        txt_cor.setText(produto.getCor());
        txt_unitario.setText(produto.getValorCm().toString());
    }//GEN-LAST:event_txt_produtosActionPerformed

    private void txt_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empresaActionPerformed
        String nomeEmpresa = txt_empresa.getSelectedItem().toString();
        ClienteBLL cb = new ClienteBLL();
        ClienteDTO cliente = cb.listaClienteNome(nomeEmpresa);
        txt_solicitante.setText(cliente.getContato());
    }//GEN-LAST:event_txt_empresaActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(!txt_empresa.getSelectedItem().equals("-")){
        String dt_entrada = txt_dtEntrada.getText().trim();
        String empresa = txt_empresa.getSelectedItem().toString();
        String servico = txt_servico.getSelectedItem().toString();
        String responsavel = txt_responsavel.getText();
        String solicitante = txt_solicitante.getText();
        String observacoes = txt_observacoes.getText();
        String qtd = txt_qtd.getText();
        String unitario = txt_unitario.getText();
        String totalCalc = txt_totalCalc.getText();
        SimpleDateFormat fd = new  SimpleDateFormat("dd/MM/yyyy");
        Date texto = txt_entrega.getDate();
        String data1 = fd.format(texto);
        //this.tb_os.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_os.getModel();
        //modelo.setNumRows(0);
        modelo.addRow(new String[]{dt_entrada,empresa,responsavel,solicitante,observacoes,qtd,unitario,totalCalc,servico,data1});
        txt_empresa.setSelectedItem("-");
        txt_produtos.setSelectedItem("-");
        txt_servico.setSelectedItem("-");
        txt_observacoes.setText("");
        txt_servico.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os Campos necessários!");
        
        } 
    }//GEN-LAST:event_btn_addActionPerformed
           
    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        if (this.tb_os.getSelectedRowCount() > 0) {
        ((DefaultTableModel) tb_os.getModel()).removeRow(tb_os.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void txt_qtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtdKeyReleased
        int v1 = Integer.valueOf(txt_unitario.getText());
        int v2 = Integer.valueOf(txt_qtd.getText());
        int resul;
        resul = v1*v2;
        txt_totalCalc.setText(String.valueOf(resul));
    }//GEN-LAST:event_txt_qtdKeyReleased

    private void txt_qtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtdKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_txt_qtdKeyTyped

    private void txt_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_servicoActionPerformed
        
        
        if(txt_servico.getSelectedItem().equals("Laser")){
            txt_qtd.setEnabled(false);
            txt_hora.setEnabled(true);
            txt_base.setEnabled(false);
            txt_altura.setEnabled(false);
            String NomeServico = txt_servico.getSelectedItem().toString();
            ServicosBLL cb = new ServicosBLL();
            ServicosDTO servico = cb.listaServicoNome(NomeServico);
            txt_valorH.setText(servico.getValorH().toString());
        }else if(txt_servico.getSelectedItem().equals("Impressora")){
            txt_qtd.setEnabled(false);
            txt_qtd.setEnabled(false);
            txt_hora.setEnabled(false);
            txt_base.setEnabled(true);
            txt_altura.setEnabled(true);
            String NomeServico = txt_servico.getSelectedItem().toString();
            ServicosBLL cb = new ServicosBLL();
            ServicosDTO servico = cb.listaServicoNome(NomeServico);
            txt_valorI.setText(servico.getValorI().toString());
        }else{
            txt_qtd.setEnabled(false);
            txt_hora.setEnabled(true);
            txt_base.setEnabled(false);
            txt_altura.setEnabled(false);
            String NomeServico = txt_servico.getSelectedItem().toString();
            ServicosBLL cb = new ServicosBLL();
            ServicosDTO servico = cb.listaServicoNome(NomeServico);
            txt_valorH.setText(servico.getValorH().toString());
            txt_qtd.setEnabled(false);
        }
        
        
        
    }//GEN-LAST:event_txt_servicoActionPerformed

    private void txt_horaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_horaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_txt_horaKeyTyped

    private void txt_horaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_horaKeyReleased
        double v1 = Double.valueOf(txt_valorH.getText());
        double v2 = Double.valueOf(txt_hora.getText());
        double resul;
        resul = v1*v2;
        txt_totalH.setText(String.valueOf(resul));
    }//GEN-LAST:event_txt_horaKeyReleased

    private void txt_baseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_baseKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_txt_baseKeyTyped

    private void txt_baseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_baseKeyReleased

        double v1 = Double.valueOf(txt_base.getText());
        double v2 = Double.valueOf(txt_altura.getText());
        double resul;
        resul = v1*v2;
        txt_totalI.setText(String.valueOf(resul*Double.valueOf(txt_valorI.getText())));
    }//GEN-LAST:event_txt_baseKeyReleased

    private void txt_alturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alturaKeyReleased
        double v1 = Double.valueOf(txt_base.getText());
        double v2 = Double.valueOf(txt_altura.getText());
        double resul;
        resul = v1*v2;
        txt_totalI.setText(String.valueOf(resul*Double.valueOf(txt_valorI.getText())));
    }//GEN-LAST:event_txt_alturaKeyReleased

    private void txt_alturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alturaKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_txt_alturaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_calc;
    private javax.swing.JButton btn_del;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JTable tb_os;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_base;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_cor;
    private javax.swing.JTextField txt_dtEntrada;
    private javax.swing.JComboBox<String> txt_empresa;
    private com.toedter.calendar.JDateChooser txt_entrega;
    private javax.swing.JTextField txt_hora;
    private javax.swing.JTextField txt_observacoes;
    private javax.swing.JComboBox<String> txt_produtos;
    private javax.swing.JTextField txt_qtd;
    private javax.swing.JTextField txt_responsavel;
    private javax.swing.JComboBox<String> txt_servico;
    private javax.swing.JTextField txt_solicitante;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_totalCalc;
    private javax.swing.JTextField txt_totalH;
    private javax.swing.JTextField txt_totalI;
    private javax.swing.JTextField txt_unitario;
    private javax.swing.JTextField txt_valorH;
    private javax.swing.JTextField txt_valorI;
    // End of variables declaration//GEN-END:variables
}
