
package br.com.AsuperArts.UI;

import br.com.AsuperArts.BLL.OrdemServicoBLL;
import br.com.AsuperArts.DTO.OrdemDeServicoDTO;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author casa
 */
public class Form_fecharOS extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_fecharOS
     */
    public Form_fecharOS() {
        initComponents();
        preencherTabela();
    }
    public void preencherTabela() {
        this.tb_fecharOs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_fecharOs.getModel();
        modelo.setNumRows(0);
        OrdemServicoBLL rg = new OrdemServicoBLL();
        for(OrdemDeServicoDTO servico : rg.lista()){
        modelo.addRow(new Object[]{
        servico.getId_os(),
        servico.getData_os(),
        servico.getServico(),
        servico.getEmpresa(),
        servico.getSolicitante(),
        servico.getResponsavel(),
        servico.getValor(),
        servico.getDescricao(),
        servico.getEstado()
        });
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_fecharOs = new javax.swing.JTable();

        setClosable(true);

        jButton1.setText("FecharOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Buscar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordens de Serviços em aberto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tb_fecharOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_os", "data_os", "servico", "empresa", "solicitante", "responsavel", "valor", "descricao", "estado", "data_fechada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_fecharOs);
        if (tb_fecharOs.getColumnModel().getColumnCount() > 0) {
            tb_fecharOs.getColumnModel().getColumn(0).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(1).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(2).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(3).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(4).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(5).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(6).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(7).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(8).setResizable(false);
            tb_fecharOs.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        OrdemServicoBLL rg = new OrdemServicoBLL();
        OrdemDeServicoDTO ordemDeServicoDTO = new OrdemDeServicoDTO();
        
        if(this.tb_fecharOs.getSelectedRowCount() > 0){
        int linha = this.tb_fecharOs.getSelectedRow();
        //OrdemDeServicoDTO.setId_os((int) this.tb_fecharOs.getValueAt(linha, 0));    
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(null, "deseja mesmo alterar?");
        if(resposta == JOptionPane.YES_OPTION){
                Form_ManutencaoOS manutencaoOS = new Form_ManutencaoOS();
                manutencaoOS.setVisible(true);
                manutencaoOS.setSize(800, 600);
                setandoCampos();
            }
        }else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 public void setandoCampos(){
        
        int linha = tb_fecharOs.getSelectedRow();
        Form_ManutencaoOS.txt_Num_OS.setText(tb_fecharOs.getModel().getValueAt(linha, 0).toString());
        Form_ManutencaoOS.txt_data.setText(tb_fecharOs.getModel().getValueAt(linha, 1).toString());
        Form_ManutencaoOS.txt_servico.setText(tb_fecharOs.getModel().getValueAt(linha, 2).toString());
        Form_ManutencaoOS.txt_Empresa.setText(tb_fecharOs.getModel().getValueAt(linha, 3).toString());
        Form_ManutencaoOS.txt_Solicitante.setText(tb_fecharOs.getModel().getValueAt(linha, 4).toString());
        Form_ManutencaoOS.txt_Responsavel.setText(tb_fecharOs.getModel().getValueAt(linha, 5).toString());
        Form_ManutencaoOS.txt_Valor.setText(tb_fecharOs.getModel().getValueAt(linha, 6).toString());
        Form_ManutencaoOS.txt_desc.setText(tb_fecharOs.getModel().getValueAt(linha, 7).toString());
        Form_ManutencaoOS.txt_estado.setText(tb_fecharOs.getModel().getValueAt(linha, 8).toString());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tb_fecharOs;
    // End of variables declaration//GEN-END:variables
}
