/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.AsuperArts.UI;

import br.com.AsuperArts.BLL.ServicosBLL;
import br.com.AsuperArts.DTO.ServicosDTO;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Form_Servicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Servicos
     */
    public Form_Servicos() {
        
        initComponents();
        preencherTabela();
        msg.setText("<html>Serviços prestados com valores mínimos.</html>");
    }
    public void preencherTabela() {
        
        this.tb_01.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.tb_01.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tb_01.getColumnModel().getColumn(0).setMinWidth(50);
        
        this.tb_01.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.tb_01.getColumnModel().getColumn(1).setMaxWidth(100);
        this.tb_01.getColumnModel().getColumn(1).setMinWidth(100);
        
        this.tb_01.getColumnModel().getColumn(2).setPreferredWidth(100);
        this.tb_01.getColumnModel().getColumn(2).setMaxWidth(100);
        this.tb_01.getColumnModel().getColumn(2).setMinWidth(100);
        
        this.tb_01.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.tb_01.getColumnModel().getColumn(3).setMaxWidth(100);
        this.tb_01.getColumnModel().getColumn(3).setMinWidth(100);


        //getContentPane().setBackground(new Color(255,255,255));
        this.tb_01.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) tb_01.getModel();
        modelo.setNumRows(0);
        ServicosBLL rg = new ServicosBLL();

        for (ServicosDTO servico : rg.lista01()) {
            modelo.addRow(new Object[]{
                servico.getId_servico(),
                servico.getServico(),
                servico.getValorH(),
                servico.getValorI(),
                servico.getMetro()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        radio_laser = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_valorH = new javax.swing.JTextField();
        radio_fresa = new javax.swing.JRadioButton();
        radio_impressora = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_valorI = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tb_1 = new javax.swing.JScrollPane();
        tb_01 = new javax.swing.JTable();
        msg = new javax.swing.JLabel();
        txt_base = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        txt_metro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Serviços Prestados");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("aSuperArts - Comunicação Visual & Sinalização Arquitetônica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("ID");

        jTextField1.setEditable(false);

        buttonGroup2.add(radio_laser);
        radio_laser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_laser.setText("Laser");
        radio_laser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_laserMouseClicked(evt);
            }
        });
        radio_laser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_laserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Serviços");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Valor Hora");

        txt_valorH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_valorH.setText("0,0");

        buttonGroup2.add(radio_fresa);
        radio_fresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_fresa.setText("Fresa");
        radio_fresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_fresaMouseClicked(evt);
            }
        });
        radio_fresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_fresaActionPerformed(evt);
            }
        });

        buttonGroup2.add(radio_impressora);
        radio_impressora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radio_impressora.setText("Impressora");
        radio_impressora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_impressoraMouseClicked(evt);
            }
        });
        radio_impressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_impressoraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Valor Impressão");

        txt_valorI.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_valorI.setText("0,0");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Excluir");

        tb_01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Serviço", "Valor Hora", "Valor Impressão", "Metros²"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_1.setViewportView(tb_01);
        if (tb_01.getColumnModel().getColumnCount() > 0) {
            tb_01.getColumnModel().getColumn(0).setResizable(false);
            tb_01.getColumnModel().getColumn(1).setResizable(false);
            tb_01.getColumnModel().getColumn(2).setResizable(false);
            tb_01.getColumnModel().getColumn(3).setResizable(false);
            tb_01.getColumnModel().getColumn(4).setResizable(false);
        }

        msg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        msg.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tb_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(tb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        txt_base.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_base.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_baseKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_baseKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Base");

        jLabel6.setText("Altura");

        txt_altura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_alturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_alturaKeyTyped(evt);
            }
        });

        txt_metro.setEditable(false);
        txt_metro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setText("Metros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_laser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_fresa))
                                    .addComponent(radio_impressora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_valorH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_valorI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_metro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_laser)
                            .addComponent(radio_fresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_impressora)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_valorH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_valorI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_metro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_laserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_laserMouseClicked
        
        if (!radio_laser.isSelected()){
            radio_laser.getActionCommand();
            
        }
    }//GEN-LAST:event_radio_laserMouseClicked

    private void radio_fresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_fresaMouseClicked
        if(!radio_fresa.isSelected()){
            radio_fresa.getActionCommand();
            radio_fresa.setEnabled(isIcon);
        }
    }//GEN-LAST:event_radio_fresaMouseClicked

    private void radio_impressoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_impressoraMouseClicked
        if(radio_impressora.isSelected()){
            radio_impressora.getActionCommand();
        }
    }//GEN-LAST:event_radio_impressoraMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ServicosBLL rg = new ServicosBLL();
       ServicosDTO servico = new ServicosDTO();
       if(radio_laser.isSelected()){
            servico.setServico(radio_laser.getActionCommand());
            servico.setValorH(Double.valueOf(txt_valorH.getText().replace(",", ".")));
            servico.setValorI(Double.valueOf(txt_valorI.getText().replace(",", ".")));
            servico.setMetro(Integer.valueOf(txt_base.getText()));
            rg.cadastrar(servico);
            preencherTabela();
            JOptionPane.showMessageDialog(null, "Serviço Cadastrado!");
       }else if(radio_fresa.isSelected()){
            
            servico.setServico(radio_fresa.getActionCommand());
            servico.setValorH(Double.valueOf(txt_valorH.getText().replace(",", ".")));
            servico.setValorI(Double.valueOf(txt_valorI.getText().replace(",", ".")));
            servico.setMetro(Integer.valueOf(txt_base.getText()));
            rg.cadastrar(servico);
            preencherTabela();
            JOptionPane.showMessageDialog(null, "Serviço Cadastrado!");
        }else if(radio_impressora.isSelected()){
                    if(!txt_base.getText().equals("")){
                            servico.setServico(radio_impressora.getActionCommand());
                            servico.setValorH(Double.valueOf(txt_valorH.getText().replace(",", ".")));
                            servico.setValorI(Double.valueOf(txt_valorI.getText().replace(",", ".")));
                            servico.setMetro(Integer.valueOf(txt_base.getText()));
                            rg.cadastrar(servico);
                            preencherTabela();
                JOptionPane.showMessageDialog(null, "Serviço Cadastrado!");
                }else{
                     JOptionPane.showMessageDialog(null, "Campos vazio!"); 
                }
        }
        else{
           JOptionPane.showMessageDialog(null, "Selecione um serviço");
       }
       
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radio_laserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_laserActionPerformed
            txt_valorH.setEnabled(true);
            txt_valorI.setEnabled(false);
            txt_base.setEnabled(false);
    }//GEN-LAST:event_radio_laserActionPerformed

    private void radio_fresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_fresaActionPerformed
            txt_valorH.setEnabled(true);
            txt_valorI.setEnabled(false);
            txt_base.setEnabled(false);
    }//GEN-LAST:event_radio_fresaActionPerformed

    private void radio_impressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_impressoraActionPerformed
            txt_valorH.setEnabled(false);
            txt_valorI.setEnabled(true);
            txt_base.setEnabled(true);
    }//GEN-LAST:event_radio_impressoraActionPerformed

    private void txt_baseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_baseKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_txt_baseKeyTyped

    private void txt_alturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alturaKeyTyped
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_txt_alturaKeyTyped

    private void txt_baseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_baseKeyReleased
        double v1 = Double.valueOf(txt_base.getText());
        double v2 = Double.valueOf(txt_altura.getText());
        double resul;
        resul = v1*v2;
        txt_metro.setText(String.valueOf(resul));
    }//GEN-LAST:event_txt_baseKeyReleased

    private void txt_alturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alturaKeyReleased
        double v1 = Double.valueOf(txt_base.getText());
        double v2 = Double.valueOf(txt_altura.getText());
        double resul;
        resul = v1*v2;
        txt_metro.setText(String.valueOf(resul));
    }//GEN-LAST:event_txt_alturaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel msg;
    private javax.swing.JRadioButton radio_fresa;
    private javax.swing.JRadioButton radio_impressora;
    private javax.swing.JRadioButton radio_laser;
    private javax.swing.JTable tb_01;
    private javax.swing.JScrollPane tb_1;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_base;
    private javax.swing.JTextField txt_metro;
    private javax.swing.JTextField txt_valorH;
    private javax.swing.JTextField txt_valorI;
    // End of variables declaration//GEN-END:variables
}
